import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#ffffff',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
  },
  title: {
    fontSize: 30,
    fontWeight: "300",
    color: '#000000',
    flex: 1,
    fontFamily: "System",
    letterSpacing: -1,
  },
  filterButton: {
    backgroundColor: '#ffffff',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  // Stili per il modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },  modalContent: {
    width: '90%',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    overflow: 'hidden',
    maxHeight: '80%',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e5e9',
    backgroundColor: '#ffffff',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '300',
    color: '#000000',
    fontFamily: "System",
    letterSpacing: -0.5,
  },
  closeButton: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    backgroundColor: 'transparent',
  },
  closeButtonText: {
    fontSize: 24,
    color: '#666666',
    fontWeight: '300',
  },
  modalBody: {
    padding: 24,
    maxHeight: 400,
  },
  modalFooter: {
    padding: 24,
    borderTopWidth: 1,
    borderTopColor: '#e1e5e9',
    alignItems: 'center',
  },
  applyButton: {
    backgroundColor: '#000000',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 24,
    width: '100%',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,    shadowRadius: 12,
    elevation: 3,
  },
  applyButtonText: {
    color: '#ffffff',
    fontWeight: '400',
    fontSize: 17,
    fontFamily: "System",
  },  // Stili per i filtri
  filterTitle: {
    fontSize: 18,
    fontWeight: '400',
    color: '#000000',
    marginBottom: 16,
    fontFamily: "System",
  },
  filterSection: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e5e9',
    marginBottom: 12,
  },
  chipsContainer: {
    flexDirection: 'row',
    paddingVertical: 8,
    flexWrap: 'wrap',
  },
  filterChip: {
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginRight: 10,
    marginBottom: 8,
    backgroundColor: '#ffffff',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  filterChipText: {
    fontSize: 15,
    color: '#666666',
    fontWeight: '400',
    fontFamily: "System",
  },  orderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 8,
  },
  orderButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginHorizontal: 6,
    borderWidth: 1.5,
    borderColor: '#e1e5e9',
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: '#ffffff',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  activeOrderButton: {
    backgroundColor: '#f8f8f8',
    borderColor: '#000000',
  },
  orderButtonText: {
    fontSize: 15,
    color: '#666666',
    fontWeight: '400',
    fontFamily: "System",
  },
  activeOrderText: {
    color: '#000000',
    fontWeight: '500',
  },
  // Stili per i filtri attivi
  activeFilterContainer: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e1e5e9',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  activeFilterText: {
    color: '#000000',
    fontWeight: '400',
    fontSize: 16,
    marginBottom: 12,
    fontFamily: "System",
  },  activeFilterChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  activeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    marginRight: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e1e5e9',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  activeChipText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '400',
    marginRight: 8,
    fontFamily: "System",
  },
  clearFilterButton: {
    color: '#666666',
    fontSize: 18,
    fontWeight: '400',
    marginLeft: 4,
  },
  emptyListContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    margin: 16,
    borderWidth: 1,
    borderColor: '#e1e5e9',  },
  emptyListText: {
    color: '#666666',
    fontSize: 17,
    textAlign: 'center',
    fontFamily: "System",
    fontWeight: '300',
  },
  addButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: "#000000",
    width: 56,
    height: 56,
    borderRadius: 28,    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },  addButtonIcon: {
    width: 28,
    height: 28,
  },
  scrollContainer: {
    flex: 1,
    width: '100%',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '400',
    color: '#000000',
    marginTop: 20,
    marginBottom: 16,
    paddingLeft: 8,
    fontFamily: "System",
    letterSpacing: -0.3,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: '#e1e5e9',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
});